### ISSUE TITLE
Extend error.CreateOptions.message to support object

### ISSUE THREAD

**Issue by yuhuiX** [headintheclouddev/typings-suitescript-2.0#112]
Currently the NetSuite error module's (error.d.ts) `create()` function has to be invoked with `message` of type string.
In fact, we could also pass an object for the `message` field, which then NetSuite stringifies it in the output log, which is a nicer structure (JSON) for parsing, when having a lot of information for error debugging using JSON rather than long string with `\"` inside.

Could you please extend the `message` field of `CreateOptions` to support also objects, or use `message: any`?

**Comment by MrRob** [comment]
Hello,

Is there any reason that you wouldn't want to just use JSON.stringify() on your object, so you could pass it in as a string?

I tried using an object in the message, like this:
`error.create({ name: 'ROBBIE_TEST', notifyOff: true, message: { test: 'Oops' } })`

And it came through weird in the execution log, like this: 
`{"type":"error.SuiteScriptError","name":"ROBBIE_TEST","message":"{test=Oops}"...`

So it seems like you wouldn't really be able to parse the error result anyway.  Let me know what you think about converting the object a string beforehand.  Ideally we like to have the module definition here match NetSuite's API definition.

**Comment by yuhuiX** [comment]
Hi,

the reason for preferring setting error objects in our projects is that we have a try catch block in the entry points, and also try catch blocks in some smaller sub functions.

The error handling in sub functions are usually used for data validation, and throw error for invalid data.
The error handling in the entry point (usually for catching unknown NetSuite errors) would catch the errors in sub functions, and rethrow it by adding additional useful information for debugging, such as the record ID or debugging related data, at the end notify the developers.

The benefit using a `error.create({name, message: errorOrCustomObject})` is that it would keep the stack trace automatically (in the object), and logged by NetSuite as a JSON object (although containing weird `"message":"{test=Oops}"`).
However, using string would need more effort in decoding all these information.

**Comment by johnogle222** [comment]
It sounds like there's some special convenience handling by NetSuite that goes on here and I can see the value add to it. I personally don't think I would rely on it but I get the point on this one.

Would changing the signature to `#create({name: string, message: string | Error | SuiteScriptError | UserEventError})` be a decent compromise?

**Comment by yuhuiX** [comment]
Here are some samples for clarity:
```javascript
// error handling in a sub function
catch (err) {
  throw errorModule.create({
    name: 'WRONG_JOURNAL_FILTER',
    message: err,
  });
}
```
```javascript
// error handling in an entry point function
catch (err) {
  throw errorModule.create({
    name: 'XXX_SS_ERROR',
    message: {
      recordId, // or any data for easier debugging
      err,
    },
  });
}
```

It would be great if the message property of `errorModule.create(callee)` would be supported in both cases

**Comment by MrRob** [comment]
I like @johnogle222's idea here, would that work for you @yuhuiX ?

**Comment by yuhuiX** [comment]
The suggested solution looks great, thanks.

Our team is also considering keeping only the error object in the message, and moving the debugging related information from object message to something different, as we are also not sure how NetSuite would change the handling of message as object in the future or not.

**Comment by MrRob** [comment]
Okay, done!

**Comment by ShawnTalbert** [comment]
If NS isn't showing _specific special behavior for just these types_: `Error | SuiteScriptError | UserEventError` then we probably shouldn't be so explicit in this declaration. If NS supports any old object (it does some sort of serialization on it when logging) then the type should indicate such.

Should this `message` prop be typed more like `string | object`, and mention that NS serializes an object if passed in the JSDocs?

It is misleading to suggest _specific types_ here unless we've evidence that those are the only types that this `message` property supports. 

All said, I believe typing the `message` property differently than the official docs is a mistake. I agree with @MrRob that using `JSON.stringify()` is a better way to go because:
* does not rely on mysterious undocumented NS behavior 😮 
* results in a message string that can be later `JSON.parse()'d if desired
* does not wander from the documented typing for `message` (i.e. `string`).
* won't break when NS changes that undocumented weird serialization

**Comment by MrRob** [comment]
@ShawnTalbert Your suggestion sounds good to me.  Want to submit a pull request for that?
