### ISSUE TITLE
"error TS2307: Cannot find module" 

### ISSUE THREAD

**Issue by chauhanvats3** [headintheclouddev/typings-suitescript-2.0#125]
Hi,
I followed the readme file to the word , and when i compiled my TS file using the tsc command, it showed an error that it can't find modules stated.
I tried changing baseUrl and paths properties in tsconfig.json of my project.
I even went and changed the relative path to the more relevant one for that file (e.g. changed "./encode" to "../N/encode") in all the TS files inside netsuite-types folder, which fixed the errors, but is not a solution.
Attached is an image of the error.
![Screenshot (64)](https://user-images.githubusercontent.com/25562174/70169769-7ab78b80-16f1-11ea-8b0b-348651c79db2.png)

**Comment by MrRob** [comment]
Hello!  So, instead of using tsc to upload, you need to use the gulp build-and-upload command.  In VS Code, you can set this up by adding a tasks.json file to your .vscode folder.  Then you should be able to use the build keyboard shortcut (command-shift-B for me) to trigger a file upload.  Here's how the tasks.json should look:
<img width="1908" alt="Screenshot 2019-12-05 at 09 52 15" src="https://user-images.githubusercontent.com/448678/70224570-63a28900-1745-11ea-8bf3-de7e0bb8fccf.png">

Also if you haven't watched it yet, check out the YouTube video on setting up our build environment.  Its geared for WebStorm, but will work the same for VS Code if you add in that tasks.json file: https://www.youtube.com/watch?v=yDw4ex8rlCA&t=247s
