### ISSUE TITLE
mapContext interface issue

### ISSUE THREAD

**Issue by darrenhillconsulting** [headintheclouddev/typings-suitescript-2.0#22]
In the typings-suitescript-2.0/N/index.d.ts, the **write** function of the **mapContext** interface should have the value parameter as **any**, its currently **string**

**Comment by darrenhillconsulting** [comment]
Same goes with the **write** function of the **reduceContext** interface.  It should have the value parameter as **any**, its currently **string[]**

**Comment by ShawnTalbert** [comment]
can we do better than the **any** catchall?

**Comment by johnogle222** [comment]
This one I conceptually go back and forth on. Technically **any** values are valid in the write function, but internally NetSuite is going to run any non-strings through JSON.stringify before it goes into **reduce**. Because of this I personally consider it a best practice to handle any conversion to a string value by the developer and avoid any quirkiness in NetSuite's implementation. Plus it forces you to think about the fact that you're ultimately writing a string value here so you will need to handle it as a string in the reduce phase.

The **reduceContext** value really is a **string[]** in all of my testing here, even if there is a single value that was written for a key. Unless this changed in 2016.2 I don't think this should be modified.

**Comment by johnogle222** [comment]
Any thoughts or comments on mapContext.any?

I think reduceContext.value shouldn't be updated but I'm open for comments on that as well.

**Comment by darrenhillconsulting** [comment]
Strong argument @johnogle222, and ya ... we can do better than **any** (that was pulled directly from Netsuite documentation).  However, JSON.stringify returns a **string**, not **string[]** ... and I hate 'casting' in Typescript.  Thoughts?

**Comment by johnogle222** [comment]
Yeah mapContext.write takes a string for a key and a string for a value currently (in this repo at least). So you can JSON.stringify into this no problem.

reduceContext.values is a string[] containing all of the values that were written for the unique key that was passed in. You would want to JSON.parse(ctx.values[0]) if you know there's only ever a single one (or loop over the array obviously if there are more).
