### ISSUE TITLE
In the /N/search.d.ts

### ISSUE THREAD

**Issue by darrenhillconsulting** [headintheclouddev/typings-suitescript-2.0#31]
Line 222:

I think should read like .. 

interface SearchCreateOptions {
    type: Type | string;
    filters?: (Filter[] | Object[]);
    filterExpression?: Object[];
    columns?: (Column[] | Object[]);
    title?: string;
    id?: string;
    isPublic?: boolean;
}

**Comment by darrenhillconsulting** [comment]
Also, under the Type .. at line 373

TRANSACTION_SEARCH ... should just be TRANSACTION

**Comment by johnogle222** [comment]
Hi Darren,

I updated N/record.Type and N/search.Type with the latest enum list from the docs in 2016.2.7. That should be good to go now.

For SearchCreateOptions, I've added the isPublic property that missing previously. The columns type is set as Array<string | Column> because it can literally be an array of strings:

`['tranid', 'name', 'amount']`

or an array of Column objects:

`[N_search.createColumn({name: 'tranid'})]`

or, because Column is an interface in this library, an array of Column-like objects:

`[{name: 'tranid'}]`

This should already be the behavior you're looking for. Let me know if there's a use case that isn't working for you though!

Thanks,
John
